### ISSUE TITLE
Error in replaying some macros

### ISSUE THREAD

**Issue by janko-m** [bruno-/vim-husk#4]
I have text:

```
"foobar"
```

And I wanted to record a macro that will convert it to LaTeX's smart quotes: ``` ``quotes''```. I positioned myself on the first double quote, and did:

1. `qq` (record to register "q")
2. ```s``<Esc>```
3. `f"`
4. `s''<Esc>`
5. `q` (stop recording)

However, when I replay the macro on this quoted text again, I get the following:

```
``<F34>"s''foobar"
```

(I'm sure that it's coming from `vim-husk`, because I commented out the rest of my `.vimrc` when testing.)

**Comment by bruno-** [comment]
Hey, I was partly aware of this issue (as reported to tpope in [this vim-rsi issue](https://github.com/tpope/vim-rsi/issues/13)), but I had no idea it could also happen with this plugin since it uses only command mode mappings.

So, as always, thanks for reporting and for the clear issue description.

**Comment by janko-m** [comment]
Thanks!

Yeah, I was also suprised, being that there are only command mode mappings.
